### ISSUE TITLE
Unable to connect to any station

### ISSUE THREAD

**Issue by mominkhan93** [riclolsen/qtester104#3]
I am not able to connect to my RTU panel. Screenshot is attached.
![image](https://github.com/riclolsen/qtester104/assets/144096301/929073a0-e578-4a58-8e2d-e1a06bdb1ea7)

**Comment by riclolsen** [comment]
Hi.
This version is pretty old, try a new one from the releases section.
Use the "Log messages" to view possible error messages.
Please check
- IP Address / TCP Port from RTU
- Connectivity, do a ping test to the RTU IP
- Firewall
- Possible client IP whitelist in the RTU
- Try another tool such as https://www.mz-automation.de/communication-protocols/iec-60870-5-101-104-test-tool/

**Comment by mominkhan93** [comment]
Issue was on my side. RTU can only be accessed through fix client IPs.
