### ISSUE TITLE
Qt Tip Error

### ISSUE THREAD

**Issue by PythonWanna** [riclolsen/qtester104#4]
![image](https://github.com/riclolsen/qtester104/assets/31816153/f276bf1d-e5c4-4e35-95e3-091ce88a62de)

**Comment by PythonWanna** [comment]
![image](https://github.com/riclolsen/qtester104/assets/31816153/739753c7-5482-4d2b-969c-4a74abe39580)

**Comment by riclolsen** [comment]
Hi!
This warning is about trying to change the socket thread that is not possible the way it is implemented. I will either fix it or give up on changing the thread to remove the warning. It does not affect the functioning of the tool. Possibly with a second thread the socket performance would be more independent of the UI updating.

**Comment by PythonWanna** [comment]
> Hi! This warning is about trying to change the socket thread that is not possible the way it is implemented. I will either fix it or give up on changing the thread to remove the warning. It does not affect the functioning of the tool. Possibly with a second thread the socket performance would be more independent of the UI updating.

Hi, you are right, I‘m just starting to learn IEC104, your tool is very pragmatic, I'm going to get serious about this tool. thanks for you reply.
