### ISSUE TITLE
C_SC_TA_1 and other commands with time tag do not set the DST flag

### ISSUE THREAD

**Issue by gnijieb** [riclolsen/qtester104#5]
Example: https://github.com/riclolsen/qtester104/blob/3726e96cd90bb3a76eae55583cea8fc189c7c483/iec104_class.cpp#L2707

The flag is always set to 0 (non DST).

This results in all commands being interpreted on the slave side with the timestamp being off 3600 seconds during DST (in my case GMT+1).
For commands with time to be accepted by a slave the timetag has to be within a certain period compared to the slaves time, otherwise the command will be discarded.

![image](https://github.com/user-attachments/assets/f7cb2646-0f38-46cd-ab85-fc5955add288)

A fix could be as easy as using the .tm_isdst flag, but I'm not sure whether localtime sets this correctly.

**Comment by riclolsen** [comment]
[bin.zip](https://github.com/user-attachments/files/17132138/bin.zip)

Hi!
Can you please test if this updated version can solve the problem?

**Comment by gnijieb** [comment]
Hi, yes it does. The DST flag is now set in commands received in the slave.

**Comment by riclolsen** [comment]
Ok, repo and release updated.
